german translation
CheckiO-Missions/checkio-task-stick-sawing pull request #2
Opened 2016-09-29 17:24 UTC by GiForce

- de/info/task_description.html
- de/info/task_short_description.html

2016-09-29 19:08 UTC, DahliaSR commented
Closes CheckIO-to-German/Roadmap#83

2016-09-29 21:06 UTC, DahliaSR requested changes
First Review!

2016-09-29 21:06 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    <p style="float: right">
to: `<p style="text-align: right">`
This will prevent the annotation from floating into the next paragraph.

2016-09-29 21:06 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Wir lieben Zahlenreihen und speziell die Dreieckszahlen (<a href="https://de.wikipedia.org/wiki/Dreieckszahl">mehr
> ... und speziell die Dreieckszahlen `(<a href="https://de.wikipedia.org/wiki/Dreieckszahl">mehr über Dreieckszahlen auf Wikipedia</a>)`

to: ... und die `<a href="https://de.wikipedia.org/wiki/Dreieckszahl">Dreieckszahlen</a>)`

This shorter, and the link is still clear.

2016-09-29 21:06 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Die Teile müssen alle verschiedene Längen haben (keine Wiederholung).
This time in german... easier to explain!

> Die Teile müssen alle ...

Das ist doppelt gemoppelt, wie man so schön sagt. _alle_ bezieht sich auf _Die Teile_.
Es sollte also wie folgt lauten:
_Alle Teile müssen verschiedene Längen haben_ **oder** _Die Teile müssen verschiedene Längen haben_

2016-09-29 21:06 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    absteigender Folge) oder eine leere Liste.
`aufsteigender Folge`
Ascending means "aufsteigend"

I would prefer '(aufsteigend sortiert)', this is shorter but still clear.

2016-09-29 21:06 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Eine Dreieckszahl ist gleich der Anzahl Teile um ein gleichseitiges Dreieck zu legen.
replace with:
`Eine Dreieckszahl ist eine Zahl, die der Summe aller Zahlen von 1 bis zu einer Obergrenze _n_ entspricht. Beispielsweise ist die 10 eine Dreieckszahl, da _1 + 2 + 3 + 4 = 10- ist.
Die ersten Dreieckszahlen sind: 0, 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...`

2016-09-29 21:06 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Dazu eine Anwendung der realen Welt:
Sometime word by word translations are :hankey: !

what about:
`Dazu ein Beispiel aus der realen Welt:`

2016-09-29 21:06 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    In kompetitiven Wettkämpfen, die in Gruppenspielen als Rundenturnier ausgetragen werden, ist
1. In english "competitive" means "hart umkämpft". I would delete "kompetitiven"
1. `die in Gruppenspielen als Rundenturnier ausgetragen werden` - delete `in Gruppenspielen` (this is a bad machine translation)

2016-09-29 21:44 UTC, GiForce commented on translations/de/info/task_description.html
> +    In kompetitiven Wettkämpfen, die in Gruppenspielen als Rundenturnier ausgetragen werden, ist
1. I don't think so [dictionary](http://www.dict.cc/?s=competitive)
2. Yea, I can do that. I found it unnecessary in the original anyway.

2016-09-29 21:46 UTC, GiForce commented on translations/de/info/task_description.html
> +    Dazu eine Anwendung der realen Welt:
That's not true, that would have been: "Hier ist eine echte Welt Anwendung"!
But sure, I can go further -.o

2016-09-29 21:50 UTC, GiForce commented on translations/de/info/task_description.html
> +    Eine Dreieckszahl ist gleich der Anzahl Teile um ein gleichseitiges Dreieck zu legen.
No, I don't want to repeat the obvious from wikipedia.
The original points explicitly the idea to form an equilateral triangle. This is also found in the wiki article, but why shouldn't I stay with the idea from the orignal?

2016-09-29 21:50 UTC, GiForce commented on translations/de/info/task_description.html
> +    absteigender Folge) oder eine leere Liste.
no idea what I was thinking

2016-09-29 21:55 UTC, GiForce commented on translations/de/info/task_description.html
> +    <p style="float: right">
ok. As much trust there is ;)

2016-09-29 22:14 UTC, GiForce commented on translations/de/info/task_description.html
> +    Eine Dreieckszahl ist gleich der Anzahl Teile um ein gleichseitiges Dreieck zu legen.
Made a better suggestion, check it out.

2016-09-30 20:14 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    absteigender Folge) oder eine leere Liste.
:stuck_out_tongue_winking_eye:

2016-09-30 20:17 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Wir lieben Zahlenreihen und speziell die Dreieckszahlen (<a href="https://de.wikipedia.org/wiki/Dreieckszahl">mehr
:+1:

2016-09-30 20:17 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Die Teile müssen alle verschiedene Längen haben (keine Wiederholung).
:+1:

2016-09-30 20:22 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Die Anzahl der Steine, die man zum Legen eines gleichseitigen Dreiecks benötigt,
:+1:

2016-09-30 20:22 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    In kompetitiven Wettkämpfen, die in Gruppenspielen als Rundenturnier ausgetragen werden, ist
1. In this cas it's question of the context.  
Kann denn ein Wettkampf **nicht** kompetitiv sein?  
But I like your solution for it.

2016-09-30 20:23 UTC, DahliaSR approved these changes
Nice!
@oduvan :shipit:

2016-09-30 20:23 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    In kompetitiven Sportarten, die als Rundenturnier ausgetragen werden, ist
:+1:

2016-10-12 08:46 UTC, merged